spring:
  application:
    name: restaurant-service

  datasource:
    url: jdbc:postgresql://localhost:5432/foodkart_restaurant
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info